// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Example.Tests")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.Junit.Expecto.TestLogger")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-08T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","50393b9290bcf8c019ff232b7adc21ec3fffa6e6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Example.Tests"
    let [<Literal>] AssemblyProduct = "BinaryDefense.Junit.Expecto.TestLogger"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-08T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "50393b9290bcf8c019ff232b7adc21ec3fffa6e6"
