// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("BinaryDefense.Junit.Expecto.TestLogger.Tests")>]
[<assembly: AssemblyProductAttribute("BinaryDefense.Junit.Expecto.TestLogger")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-01-29T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","7a28a03ecf7ca4351b529f9843577816d0ffc82e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BinaryDefense.Junit.Expecto.TestLogger.Tests"
    let [<Literal>] AssemblyProduct = "BinaryDefense.Junit.Expecto.TestLogger"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-01-29T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyInformationalVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "7a28a03ecf7ca4351b529f9843577816d0ffc82e"
